name: DominionTweak
version: '1.0.0'
main: me.xydesu.dominiontweak.DominionTweak
api-version: '1.20'
depend:
  - Dominion
folia-supported: true
commands:
  dt:
    description: 管理 DominionTweak 功能 (封鎖/解封玩家等)
    aliases:
      - dominiontweak
permissions:
  dominiontweak.bypass:
    description: 允許繞過領地的所有限制 (如 walk, tp)
    default: op
  dominiontweak.bypass.walk:
    description: 允許繞過領地的 walk 限制
    default: op
  dominiontweak.bypass.tp:
    description: 允許繞過領地的 tp 限制
    default: op
